version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ctaaapi-production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Mount service account file instead of credentials.json
      - ./service-account.json:/usr/src/app/service-account.json:ro
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ctaaapi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "app=CTAAAPI"
      - "environment=production"

networks:
  ctaaapi-network:
    driver: bridge