name: Test Runner

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Test runner connection
      run: |
        echo "Runner is working!"
        echo "Current directory: $(pwd)"
        echo "Current user: $(whoami)"
        echo "Docker version:"
        docker --version